#!/bin/bash

#add npm and node to path
export NVM_DIR="/root/.nvm"
export PATH="$NVM_DIR/versions/node/v22.22.2/bin:/usr/local/bin:/usr/bin:/bin"

PM2_CMD="/root/.nvm/versions/node/v22.22.2/bin/pm2"

mv /opt/frontend-apps/admin-kourierly/build/* /var/www/html/admin-kourierly/
cd /var/www/html
$PM2_CMD start serve --name "k-admin" -- -s admin-kourierly -l 5000
rm -rf /opt/frontend-apps/admin-kourierly
service nginx restart