#!/bin/bash
export NVM_DIR="/root/.nvm"
export PATH="$NVM_DIR/versions/node/v22.22.2/bin:/usr/local/bin:/usr/bin:/bin"

PM2_CMD="/root/.nvm/versions/node/v22.22.2/bin/pm2"

cd /var/www/html
$PM2_CMD stop k-admin
$PM2_CMD delete k-admin