version: 0.0
os: linux

files:
  - source: /
    destination: /opt/pm2_test

hooks:
  # AfterInstall:
  #   - location: test-scripts/install_dependencies.sh
  #     timeout: 300
  #     runas: root

  ApplicationStart:
    - location: test-scripts/start
      timeout: 300
      runas: root

  ApplicationStop:
    - location: test-scripts/stop
      timeout: 300
      runas: root